# Generated by Django 3.1.3 on 2020-11-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admindb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vno', models.CharField(max_length=50)),
                ('oname', models.CharField(max_length=50)),
                ('mname', models.CharField(max_length=50)),
                ('mno', models.CharField(max_length=50)),
                ('pyear', models.CharField(max_length=50)),
                ('lno', models.CharField(max_length=50)),
                ('foul', models.CharField(max_length=50)),
                ('fine', models.CharField(max_length=50)),
                ('oaddress', models.CharField(max_length=100)),
                ('cdetail', models.CharField(max_length=50)),
                ('lissuedate', models.DateField()),
                ('lexpiredate', models.DateField()),
            ],
        ),
    ]
